FROM nevinee/qbittorrent
ENV IYUU_REPO_URL=https://github.com/ledccn/IYUUPlus.git
RUN apk add --update --no-cache \
       tar \
       libressl \
       zip \
       unzip \
       git \
       composer \
       php7 \
       php7-curl \
       php7-dom \
       php7-json \
       php7-mbstring \
       php7-openssl \
       php7-opcache \
       php7-pdo \
       php7-pdo_sqlite \
       php7-phar \
       php7-pcntl \
       php7-posix \
       php7-simplexml \
       php7-sockets \
       php7-session \
       php7-zip \
       php7-zlib \
       php7-xml \
    && git config --global pull.ff only \
    && git clone ${IYUU_REPO_URL} /iyuu \
    && echo -e "upload_max_filesize=100M\npost_max_size=108M\nmemory_limit=1024M\ndate.timezone=${TZ}" > /etc/php7/conf.d/99-overrides.ini \
    && rm -rf /var/cache/apk/* /tmp/*
COPY s6-overlay-iyuu /
VOLUME ["/iyuu"]
