#!/usr/bin/with-contenv bash

add_package() {  
    if [[ $INSTALL_PYTHON == true ]]; then
        echo "Install python3..."
        apk add --update --no-cache python3
    fi
}

add_package 2>&1 | sed "s#^#[cont-init.d] $(basename $0): \1#g"
