#!/usr/bin/with-contenv sh

fixuser() {
    echo '修改文件夹 "/config, /app"的所有者为 "csf" 用户...'
    groupmod -o -g "${PGID}" csf
    usermod -o -u "${PUID}" csf
    chown -R csf:csf /config /app
}

fixuser 2>&1 | sed "s#^#[cont-init.d] $(basename $0): \1#g"