#!/usr/bin/with-contenv bash

fix_config() {
    BT_PORT=${BT_PORT:-34567}
    WEBUI_PORT=${WEBUI_PORT:-8080}
    if [ ! -s /data/config/qBittorrent.conf ]; then
        echo "Initializing qBittorrent configuration..."
        cat > /data/config/qBittorrent.conf << EOF
[General]
ported_to_new_savepath_system=true

[AutoRun]
enabled=true
program=dl-finish \"%I\"

[LegalNotice]
Accepted=true

[Preferences]
Connection\Interface=
Connection\PortRangeMin=${BT_PORT}
Connection\UseUPnP=false
Downloads\SavePath=/data/downloads
General\Locale=zh_CN
General\UseRandomPort=false
Queueing\QueueingEnabled=false
WebUI\Address=*
WebUI\AlternativeUIEnabled=false
WebUI\Enabled=true
WebUI\LocalHostAuth=false
WebUI\Port=${WEBUI_PORT}
EOF
    fi

    echo "Overriding required parameters..."
    sed -i "{
        s!ported_to_new_savepath_system.*!ported_to_new_savepath_system=true!g;
        s!Connection\\\PortRangeMin=.*!Connection\\\PortRangeMin=${BT_PORT}!g;
        s!WebUI\\\Enabled=.*!WebUI\\\Enabled=true!g;
        s!WebUI\\\Port=.*!WebUI\\\Port=${WEBUI_PORT}!g;
        s!WebUI\\\LocalHostAuth=.*!WebUI\\\LocalHostAuth=false!g;
    }" /data/config/qBittorrent.conf

    major_ver=$(qbittorrent-nox --version | sed 's|qBittorrent v||' | awk -F. '{print $1}')
    minor_ver=$(qbittorrent-nox --version | sed 's|qBittorrent v||' | awk -F. '{print $2}')

    if [[ $major_ver -eq 4 && $minor_ver -ge 5 ]]; then
        sed -i -E 's|General\\Locale=.+|General\\Locale=zh_CN|' /data/config/qBittorrent.conf
    elif [[ $major_ver -eq 4 && $minor_ver -lt 5 ]]; then
        sed -i -E 's|General\\Locale=.+|General\\Locale=zh|' /data/config/qBittorrent.conf
    fi
}

fix_config 2>&1 | sed "s#^#cont-init: info: $(realpath $0): \1#g"
