#!/usr/bin/with-contenv bash

fix_user() {
    PUID=${PUID:-1000}
    PGID=${PGID:-100}
    echo "Change owner to user qbittorrent..."
    echo "PUID=${PUID}"
    echo "PGID=${PGID}"
    groupmod -o -g "${PGID}" qbittorrent
    usermod -o -u "${PUID}" qbittorrent
    chown -R qbittorrent:qbittorrent "${QBITTORRENT_HOME}" /data
}

fix_user 2>&1 | sed "s#^#[cont-init.d] $(basename $0): \1#g"
